version: "3.8"

services:
  mysql:
    container_name: awardrobe-mysql
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dev
    ports:
      - 3306:3306

  meilisearch:
    container_name: awardrobe-meilisearch
    image: getmeili/meilisearch:v1.2
    ports:
      - 7700:7700
    environment:
      - MEILI_NO_ANALYTICS=true

  postgres:
    container_name: awardrobe-postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
